config.custom:
  path: '/admin/config/custom-form'
  defaults:
    _form: '\Drupal\custom_config_form\Form\CustomConfigForm'
    _title: 'Custom Configuration Form'
  requirements:
    _permission: 'administer site configuration'
